openapi: 3.0.3
info:
  title: EazyShop Products APIs Definition
  description: |
      # About Us
     
  termsOfService: https://eazyshop.com/terms/
  x-custom-info:
    comment: Some comments
    developers:
      - name: John Doe
        email: john@doe.com
      - name: Jane Doe
        email: jane@doe.com
  contact:
    name: API Support
    url: https://www.eazyshop.com/support
    email: support@eazyshop.com
  license:
    name: EazyShop License
    url: https://www.eazyshop.com/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: External Documentation
  url: https://example.com
servers:
  - url: https://b4xqmvix7c.execute-api.us-west-2.amazonaws.com/dev/serverlessSetup
    description: Development server


paths:
  /hello:
    get:
      tags:
        - Categories
      summary: List all catgories
      description: Returns the list of categories supported by EazyShop
      responses:
        '200':
          description: hello message
          content:
            application/json:
              schema:
                type: string
               
             
       
 
  
   